### ISSUE TITLE
What is `orcid_doi` actually doing?

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/rorcid#10]
It is not clear to me what orcid_doi actually does, or how the search results are meaningful.  The DOI: [10.1890/130001](http://dx.doi.org/10.1890/130001) goes to a paper in *Frontiers in Ecology and Evolution* that was obviously written by a very talented person, but when I search for the DOI I get a list that only vaguely resembles the author list, and includes only one of the authors of the paper:

```
orcid_doi(dois = '10.1890/130001', fuzzy = FALSE)[[1]]$data$'personal-details.given-names'

 [1] "Judit"        "Simon"        "José Gabriel" "Sebastian"    "Harry"        "Daimeng"     
 [7] "Luchino"      "Meteb M"      "Zhen-Jun"     "Céline"     

```

So what is actually happening here?

**Comment by SimonGoring** [comment]
To follow up, if I actually search for the DOI on ORCiD's home page in the search bar I get myself as the first hit, and none of the other hits here even show up, so this API is hitting something that the front page's search bar isn't hitting and returning results with different relevance values.

**Comment by sckott** [comment]
@SimonGoring This fxn is to search for orcids given a DOI. 

Unfortunately, their website i'm guessing doesn't consume their API (just as the PLOS website doesn't consume their search API) - so results may not be the same. 

I'll have a look at the fxn. It looks like the parsing of names isn't being done correctly. I'm using `jsonlite` parser - which sometimes doesn't parse things cleanly

**Comment by SimonGoring** [comment]
I think that a bunch of this is just ORCiD being annoying.  What I expected was to see a list of all people who have that DOI in their ORCiD profiles, but I don't, it's just people who have DOIs that are somewhat similar?  So even with the fuzzy matching turned off we're still getting some kind of fuzzy matching.

**Comment by rcpeters** [comment]
Hi Guys,
Rob from ORCID. Our website actually does use the same API in this case. However the query language is bit hard to work out.  

       curl -H "Accept: application/orcid+xml" "http://pub.orcid.org/v1.1/search/orcid-bio/?q=digital-object-ids:%2210.1890/130001%22" 

Gives one exact match note the %22 double quotes. Without the double quotes solr will do fuzzy matching. I worked this out by referencing this [documentation](http://support.orcid.org/knowledgebase/articles/132354-tutorial-searching-with-the-api) page.  It's awesome to see this R Library.

Cheers,
Rob

**Comment by sckott** [comment]
hi @rcpeters woops, sorry I assumed the wrong thing :)

Thanks for the feedback - I'll debug to make this is working

**Comment by sckott** [comment]
@SimonGoring okay, reinstall and try again

@rcpeters thx for the tip about the quotes, i had `%22`, but the `httr` package url encodes for me, and I forgot, so using `"` directly

**Comment by SimonGoring** [comment]
Boom, that did it, perfectly.  Thanks @sckott and @rcpeters.  So @rcpeters I need to put the DOI into quotes on the main search bar on the Orcid website as well?

**Comment by rcpeters** [comment]
Happy to hear things are working now. I don't believe we offer/map DOI
search on the GUI. I'll bring it up in the next tech meeting. Cheers,
Rob

On Sun, Feb 8, 2015 at 9:05 PM, Simon <notifications@github.com> wrote:

> Boom, that did it, perfectly. Thanks @sckott <https://github.com/sckott>
> and @rcpeters <https://github.com/rcpeters>. So @rcpeters
> <https://github.com/rcpeters> I need to put the DOI into quotes on the
> main search bar on the Orcid website as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rorcid/issues/10#issuecomment-73458121>.
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by SimonGoring** [comment]
It's just that if you look at my profile I have collaborators on several
papers who also have ORCiDs, but you can't link to them through the paper
profile.  Does that make sense?

Simon

**Comment by rcpeters** [comment]
GUI browsability  isn't on the 2015 road map. For 2015 improving the API
browsibility beyond DOIs is. However I wouldn't be surprised if we did a
little backfilling on the GUI after the new API browsibility is
implemented.

On Mon, Feb 9, 2015 at 6:10 AM, Simon <notifications@github.com> wrote:

> It's just that if you look at my profile I have collaborators on several
> papers who also have ORCiDs, but you can't link to them through the paper
> profile. Does that make sense?
>
> Simon
> On Feb 9, 2015 12:18 AM, "Robert Peters" <notifications@github.com> wrote:
>
> > Happy to hear things are working now. I don't believe we offer/map DOI
> > search on the GUI. I'll bring it up in the next tech meeting. Cheers,
> > Rob
> >
> > On Sun, Feb 8, 2015 at 9:05 PM, Simon <notifications@github.com> wrote:
> >
> > > Boom, that did it, perfectly. Thanks @sckott <
> https://github.com/sckott>
> > > and @rcpeters <https://github.com/rcpeters>. So @rcpeters
> > > <https://github.com/rcpeters> I need to put the DOI into quotes on the
> > > main search bar on the Orcid website as well?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ropensci/rorcid/issues/10#issuecomment-73458121>.
> > >
> >
> >
> >
> > --
> > Robert Peters
> > info@rcpeters.com
> > 805.440.9056
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ropensci/rorcid/issues/10#issuecomment-73462363>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rorcid/issues/10#issuecomment-73513803>.
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by sckott** [comment]
@SimonGoring this sounds like a problem just for the web interface, yes?

**Comment by SimonGoring** [comment]
Yes, the doi search seems to work now in the package.  I get two results
from the search, one is me and one is the other co-author with an ORCiD.

On Mon, Feb 9, 2015 at 12:46 PM, Scott Chamberlain <notifications@github.com
