### ISSUE TITLE
`Error in parseJSON(txt)` error with `orcid`, 

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/rorcid#12]
This is now happening:

```
> find.simon <- orcid(query='Simon Goring')
Error in parseJSON(txt) : lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="U
                     (right here) ------^
```

The `right here` arrow should be pointing to the question mark.

**Comment by gavinsimpson** [comment]
That is working for me:

```r
> library("rorcid")
> find.simon <- orcid(query='Simon Goring')
> find.simon
<Orcid Search>
Found: 7396
Size: 10 X 29

   relevancy-score.value orcid type group-type client-type
1              0.7515224    NA   NA         NA          NA
2              0.6612253    NA   NA         NA          NA
3              0.3285365    NA   NA         NA          NA
4              0.2566062    NA   NA         NA          NA
5              0.2566062    NA   NA         NA          NA
6              0.2390788    NA   NA         NA          NA
7              0.2390788    NA   NA         NA          NA
8              0.2390788    NA   NA         NA          NA
9              0.2390788    NA   NA         NA          NA
10             0.2390788    NA   NA         NA          NA
Variables not shown: orcid-identifier.value (lgl), orcid-identifier.uri (chr),
     orcid-identifier.path (chr), orcid-identifier.host (chr), delegation
     (lgl), applications (lgl), scope (lgl), personal-details.given-names.value
     (chr), personal-details.family-name.value (chr),
     personal-details.credit-name.value (chr),
     personal-details.credit-name.visibility (lgl),
     personal-details.other-names.other-name (list),
     personal-details.other-names.visibility (lgl),
     researcher-urls.researcher-url (list), researcher-urls.visibility (lgl),
     keywords.keyword (list), keywords.visibility (lgl),
     external-identifiers.external-identifier (list),
     external-identifiers.visibility (lgl), contact-details.email (list),
     contact-details.address.country.value (chr),
     contact-details.address.country.visibility (lgl), biography.value (chr),
     biography.visibility (lgl)
> sessionInfo()
R version 3.1.1 Patched (2014-08-21 r66455)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_CA.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_CA.utf8        LC_COLLATE=en_CA.utf8    
 [5] LC_MONETARY=en_CA.utf8    LC_MESSAGES=en_CA.utf8   
 [7] LC_PAPER=en_CA.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_CA.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rorcid_0.1.7.99

loaded via a namespace (and not attached):
[1] bitops_1.0-6    devtools_1.6.1  httr_0.6.1      jsonlite_0.9.14
[5] RCurl_1.95-4.5  stringr_0.6.2   tools_3.1.1
```

**Comment by sckott** [comment]
thanks @SimonGoring for reporting, and @gavinsimpson for testing

Simon, can you paste in your sessioninfo?

**Comment by gavinsimpson** [comment]
FWIW I just updated my package library and reran the example without error.

**Comment by SimonGoring** [comment]
Yep, just updated it and it seems to work fine.  Weird.

**Comment by sckott** [comment]
glad it's fixed

**Comment by bpbond** [comment]
This error occurs for me with an updated (just downloaded) `rorcid` and `jsonlite`:

```R
> source("rorcid_network.R")
Error in parseJSON(txt) : lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="U
                     (right here) ------^
```

Session info:

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_0.9.14 rorcid_0.1.8.99 devtools_1.7.0  igraph_0.7.1   

loaded via a namespace (and not attached):
[1] httr_0.5       RCurl_1.95-4.1 stringr_0.6.2  tools_3.1.2  
```

**Comment by sckott** [comment]
@bpbond okay, try it again after reinstalling this pkg, looks like `httr_0.5`  was causing a problem, not sure why,

**Comment by bpbond** [comment]
That fixed it! Thanks, Scott.

**Comment by sckott** [comment]
great, glad it worked @bpbond

**Comment by 123vaibhav** [comment]
I am facing the similar issue as above. I have tried all the methods listed above and also other internet resources. I have updated all my packages as well as rorcid(). A brief about by issue, I am trying to read data via API and getting error as

Error: lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="u
                     (right here) ------^


Here is a sample code

library(httr)
library(jsonlite)
library(rorcid)
library(curl)

AA <- GET(url="Url along with API key")

AA_txt <- content(AA, "text")
AA_json <- fromJSON(AA_txt, flatten = TRUE)

Here is my session info

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.7.2 curl_3.1        rorcid_0.4.0    jsonlite_1.5    httr_1.3.1     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 magrittr_1.5   R6_2.2.2       tools_3.4.2    Rcpp_0.12.16   stringi_1.1.7 
[7] crul_0.5.2     stringr_1.3.0

**Comment by sckott** [comment]
@123vaibhav is this a question about this package?

**Comment by 123vaibhav** [comment]
@sckott 
I am not a master in R so I am not sure if this issue is with package or not. However as mentioned in my earlier comment I have already tried all solutions mentioned in this trail as well as other internet resources. Looking forward to your help on this matter.

Thanks in advance.

**Comment by sckott** [comment]
@123vaibhav its' not clear to me that you're actually using `rorcid` can you show me example code using `rorcid` that's causing the problem
