### ISSUE TITLE
Get employment, etc.

### ISSUE THREAD

**Issue by bomeara** [ropensci/rorcid#24]
I'm trying to use rorcid to automatically make a CV (code at https://github.com/bomeara/cv). Orcid should suffice for this: it has info on grants, employment history, etc (i.e., http://orcid.org/0000-0002-0337-5997). However, I can't seem to get at this using rorcid; in fact, I don't see a way to get at this using ORCID's API, so the problem may lie there. However, this seems like something that should be available -- am I just missing it somewhere?

**Comment by sckott** [comment]
hey brian :) let me check - what exactly can you not get at?

**Comment by sckott** [comment]
Its a complicated set of APIs - it's possible that we need to use authencation to get that information. The docs seem to indicate that any public data is available in the API calls - but employment etc. stuff isn't there - I'll keep loolking

**Comment by bomeara** [comment]
I can get my works, and my email and url, but not employment history, funding, or education.

i.e., `dput(orcid_id(orcid = "0000-0002-0337-5997", profile="bio"))` shows all I get from bio, but doesn't include this, nor does the full dump of `dput(orcid_id(orcid = "0000-0002-0337-5997", profile="profile"))`.

FWIW, this is my overall profile, which has this info: http://orcid.org/0000-0002-0337-5997 .

**Comment by bomeara** [comment]
And this is a "nice to have" sort of thing: obviously I can just write this info the old-fashioned way into a CV (and it hopefully won't change as fast as publications). Just seems logical to have a way to grab this from ORCID if it already exists.

**Comment by sckott** [comment]
> And this is a "nice to have" 

right, but needs to be sorted 🔧

**Comment by bomeara** [comment]
It may be that their 2.0 API has this, but not their 1.2. https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources/record_2.0_rc1

**Comment by rcpeters** [comment]
Everything you asked for is in both APIs `curl -H'Accept: application/xml' http://pub.orcid.org/v1.2/0000-0002-0337-5997/orcid-profile`

**Comment by bomeara** [comment]
Thanks, @rcpeters. So it could just be a matter of having rorcid process this info (while not ruling out that it already does, and I just missed this somewhere in its output).

**Comment by sckott** [comment]
ah, looks like I was dropping `orcid-activities`

**Comment by sckott** [comment]
@bomeara reinstall `devtools::install_github("ropensci/rorcid")`

```r
library(rorcid)
res <- orcid_id("0000-0002-0337-5997")
res$`0000-0002-0337-5997`$`orcid-activities`
```

**Comment by bomeara** [comment]
Perfect! Well done. Thanks, @sckott & @rcpeters!

**Comment by sckott** [comment]
glad it works.

**Comment by mfenner** [comment]
Great stuff. You might also consider pulling in info from some of the places that build profiles using ORCID, e.g. ImpactStory or Europe PMC (http://europepmc.org/authors/0000-0002-0337-5997). The latter has no API yet.

Something I am working on with ORCID is pushing (authenticated) GitHub usernames into the ORCID profile from DataCite, so in the future you will also fetch that info from ORCID and can build something nice around it. E.g. using Depsy.

**Comment by sckott** [comment]
Good ideas, but do want to stick to ORCID in this pkg - perhaps a different pkg could combine them
