### ISSUE TITLE
lexical error: invalid char in json text with `as.orcid`

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/rorcid#27]
This seems to be coming from the ORCID side (maybe?) but I'm getting it through rorcid and can't figure out what's going on.

It literally just started:

```
> as.orcid("0000-0002-2700-4605")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html><html><head><tit
                     (right here) ------^
> 
```

So it seems like a whole page is being returned instead of the original JSON.  Any thoughts?

**Comment by rcpeters** [comment]
Some is trying to send to much traffic. Ask for 1000 records and keeps
retrying regardless of the response.

On Sun, May 22, 2016 at 9:43 PM, Simon <notifications@github.com> wrote:

> This seems to be coming from the ORCID side (maybe?) but I'm getting it
> through rorcid and can't figure out what's going on.
>
> It literally just started:
>
> > as.orcid("0000-0002-2700-4605")
> Error: lexical error: invalid char in json text.
>                                        <!DOCTYPE html><html><head><tit
>                      (right here) ------^
> >
>
> So it seems like a whole page is being returned instead of the original
> JSON. Any thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rorcid/issues/27>
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by sckott** [comment]
@rcpeters DOS attack?  

@SimonGoring yeah, everything is failing, hopefully back up soon

**Comment by rcpeters** [comment]
Right now it looks to be an issue with a new server deployed to help cope
with the original issue. However since you guys are noticing the original
issue might be @SimonGoring. Let's talk later this week about what you guys
are trying to do and I can verify.

On Sun, May 22, 2016 at 9:48 PM, Scott Chamberlain <notifications@github.com
> wrote:

> @rcpeters <https://github.com/rcpeters> DOS attack?
>
> @SimonGoring <https://github.com/SimonGoring> yeah, everything is
> failing, hopefully back up soon
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rorcid/issues/27#issuecomment-220886722>
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by SimonGoring** [comment]
@rcpeters I was only calling on or two at a time.  Specifically my own & one other.

**Comment by SimonGoring** [comment]
@sckott @rcpeters the problem seems to have resolved now.  I'll close the issue since it's unrelated to the package.

**Comment by rcpeters** [comment]
Ah, that should be 100%. It looks like someone trying to compare names in
bulk. I'll keep hunting :-)

On Sun, May 22, 2016 at 9:59 PM, Simon <notifications@github.com> wrote:

> @rcpeters <https://github.com/rcpeters> I was only calling on or two at a
> time. Specifically my own & one other.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rorcid/issues/27#issuecomment-220887646>
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by sckott** [comment]
@rcpeters good luck :)

**Comment by sckott** [comment]
tests are all passing now, looks like all is good
