### ISSUE TITLE
search on works metadata

### ISSUE THREAD

**Issue by sckott** [ropensci/rorcid#33]
see http://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/15296196-search-by-works-metadata

and https://gist.github.com/sckott/41a400341180e967d5405642537b7c1e

**Comment by sckott** [comment]
> We have an update (March 2017) that the current version of the API search in 2.0 includes searching works by identifiers and title: https://members.orcid.org/api/tutorial/search-orcid-registry (All identifiers can be used. The current list is at https://pub.orcid.org/v2.0/identifiers/ )

**Comment by sckott** [comment]
@rcpeters i can't find any examples how to search on external identifiers - any examples?  i assume one has to define what identifier is being used

**Comment by rcpeters** [comment]
Documentation isn't very clear. @TomDemeranville or @caoyler can we add some clarity?

**Comment by TomDemeranville** [comment]
@sckott we are working on improving the documentation.  The id types can be found here: https://pub.orcid.org/v2.0/identifiers?locale=en

For each name, you can search for them using either self or part-of as a suffix.  e.g. 'doi-self' or 'isbn-part-of' as the field names.

**Comment by sckott** [comment]
@TomDemeranville thanks very much.

**Comment by sckott** [comment]
the issue closed  https://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/15296196-search-by-works-metadata and they say 

> We have an update (March 2017) that the current version of the API search in 2.0 includes searching works by identifiers and title: https://members.orcid.org/api/tutorial/search-orcid-registry (All identifiers can be used. The current list is at https://pub.orcid.org/v2.0/identifiers/ ) 

which already knew, but also

> We’ve also added suggestions for increasing the searchable works metadata to things to consider for future development. These would generally be understood to be the supported fields supported in ORCID (see our Works XSD: https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/record_2.0/work-2.0.xsd ).

> Note that author would generally not be one considered as we do not have an author field. We do support the addition of contributors, but do not have clear guidance on the at present— we expect this to come out of our discussions related to Project credit, etc. — see our User/Member Interface Improvements goal for 2017: https://trello.com/c/mBcwieED/10

docs: https://members.orcid.org/api/tutorial/search-orcid-registry

**Comment by sckott** [comment]
i think this is sorted now, closing
