### ISSUE TITLE
2.0 API, searching for specific fields?

### ISSUE THREAD

**Issue by cboettig** [ropensci/rorcid#36]
Looks like rocid is using 1.2 API? 2.0 supports much richer queries: http://members.orcid.org/api/tutorial/search-orcid-registry .  In particular, I'd like to be able search by user email (or user first/last name) to see if a user has an ORCID id.  (not sure how many orcid users actually expose their email in their record, maybe searching by names would be best ).  

Anyway, the current version just seems to throw NAs for the search tables (e.g. in the vignette, though maybe that's just a coercion error going on?)  Also the current search doesn't seem to specify the field, clearly it would be more reliable to indicate that, say, "Jones" is the surname.

Thoughts?  Looks like one needs to authenticate with a token to use 2.0?  may still be worth while having support for it.  Or maybe it's there and I'm just missing it?

**Comment by sckott** [comment]
Thanks for raising the issue @cboettig (related #26) have 

> the current version just seems to throw NAs for the search tables (

will have a look and fix

>  Also the current search doesn't seem to specify the field, clearly it would be more reliable to indicate that, say, "Jones" is the surname.

what "current search"?

-----

I thought 2.0 was just for members but saw this on http://members.orcid.org/api 

> Please note that we expect v1.2 to be phased out by late 2017.

so i guess we need to move to 2.0 for sure for unauthenticated as well as with auth

**Comment by sckott** [comment]
@cboettig started working on new v2 api, `devtools::install_github("ropensci/rorcid@api-v2")`

some functions may not work: identifiers, works, as.orcid, browse, check_dois, orcid_id

auth is started and is working more or less - BUT turns out auth isn't required on v2 api even though docs say it is - but it's highly encouraged, so will make it mandatory i guess soon

**Comment by cboettig** [comment]
Very cool.  Wonder if this might be useful to our interns; whom I'm hoping will help us add ORCID ids to package author metadata...

**Comment by sckott** [comment]
Yeah, could be, hopefully I can get this sorted sooner than later :)

**Comment by sckott** [comment]
using v2.1 now, closing
