### ISSUE TITLE
Orcid API changes

### ISSUE THREAD

**Issue by sckott** [ropensci/rorcid#37]
@rcpeters It appears we need to switch over to v2.0 API from v1.2, correct?  Seems that public and member will soon be only 2.0, correct?

Do you have a changelog or so?  It seems some routes in v1.2 are now gone in v2.0. e,g, `/search/orcid-bio` from v1.2 doesn't seem to exist in v2.0 - or am I wrong ?

Any update on when v1.2 will be dropped completely?

**Comment by rcpeters** [comment]
The URLs are different but the queries are the same:
`curl https://pub.orcid.org/v1.2/search/orcid-bio?q=johnson+AND+cardiology+AND+houston`
vs 
`curl https://pub.orcid.org/v2.0/search/?q=johnson+AND+cardiology+AND+houston`

2.0 will only return IDs (ideal of some integrations and less then ideal for others). I would expect v1.2 to be dropped in 2017 Q4.

**Comment by sckott** [comment]
started in 4ba436c on branch `api-v2`
