### ISSUE TITLE
Error for specific researcher

### ISSUE THREAD

**Issue by agbarnett** [ropensci/rorcid#49]
I'm getting an error for this specific researcher who has over 100 papers. The same error appears if I change the type to 'eid' or 'pmid'.

> d = works(orcid_id(orcid = "0000-0002-2787-8484"))
> dois = identifiers(d, type='doi')
Error in z[tolower(z$`external-id-type`) %in% type, "external-id-value"] : 
  incorrect number of dimensions

**Comment by sckott** [comment]
thanks @agbarnett

**Comment by sckott** [comment]
@agbarnett try again after reinstalling

**Comment by agbarnett** [comment]
Working well, thanks. Would be great to this updated on CRAN so that the shiny app works.
