### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by joneriks** [ropensci/rorcid#50]
I have successfully been using this package for quite a while (Thank you!!), but starting yesterday (after being away for a couple of weeks), I can no longer authenticate. 
I get:
"no ORCID token found; attempting OAuth authentication" it then some times just hangs there for a while and throws a 404 error (Error: Not Found (HTTP 404).  - 404 Not Found: The resource was not found.,") or it sends me to the oAuth form like before, but then returns an error of "Redirect URI doesn't match your registered redirect URIs.". In Rstudio, it then shows a prompt of "Enter authorization code: ". 

As I mentioned this has been working fine before, so I am not sure what has changed.

Also, is there any documentation on how to create the token file that is mentioned in the source code?

Thanks, 

Jonas

**Comment by sckott** [comment]
thanks @joneriks for the issue. 

Please share your `sessionInfo()` so I can see what version you have and what system you're running on. Are you using rstudio on a server, or locally on your own machine

**Comment by joneriks** [comment]
I have actually tried it on two computers with local RStudio installations, and also on a Rstudio server. I have the same issues on both setups. Here is the session info from one of the local installations:
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.18  

Let me know if I can provide anything else.

**Comment by sckott** [comment]
thanks, will have a look

**Comment by sckott** [comment]
I would strongly recommend using the token  approach, but of course the oauth needs to work once at least first. 

The docs for that are in `?auth` 

When you get this error 

> Redirect URI doesn't match your registered redirect URIs

report back here what the URL is

**Comment by joneriks** [comment]
Sorry about that, here is the correct sessionInfo():

R version 3.4.3 (2017-11-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openssl_1.0.1   lubridate_1.7.2 rorcid_0.4.0    stringr_1.3.0   purrr_0.2.4     tidyr_0.8.0     dplyr_0.7.4    
[8] readr_1.1.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     bindr_0.1.1      magrittr_1.5     hms_0.4.2        R6_2.2.2         rlang_0.2.0     
 [7] httr_1.3.1       tools_3.4.3      yaml_2.1.18      assertthat_0.2.0 tibble_1.4.2     bindrcpp_0.2.2  
[13] curl_3.2         crul_0.5.2       glue_1.2.0       stringi_1.1.7    compiler_3.4.3   pillar_1.2.1    
[19] jsonlite_1.5     pkgconfig_2.0.1 

This is the URL that shows: https://orcid.org/oauth/authorize?client_id=APP-7E02XXWNQBFNMG1B&scope=%2Fauthenticate&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code

**Comment by sckott** [comment]
so that redirect uri (`urn:ietf:wg:oauth:2.0:oob`) is for OOB Oauth and you must have had it set somehow to  - ORCID doesn't support that yet, see discussion here https://groups.google.com/forum/#!topic/orcid-api-users/tMS7-OnwOU0 

you can set the redirect uri manually and see if that works, like `orcid_auth(redirect_uri = "http://localhost:1410/")`

**Comment by joneriks** [comment]
Thanks, the last line seems to have solved my Auth issue, as I can now run for instance:
`out<-works(orcid_id("0000-0001-8446-1995"))`

However, when I try to run (ids is a list of ORCIDs):
`works_list<-lapply(ids, function(x) works(orcid_id(x)))` 
or 
`works_list<-lapply(ids, function(x) orcid_works(x))`
I now get a"Error: Not Found (HTTP 404).  - 404 Not Found: The resource was not found."
Maybe this is unrelated, but it is code/process that used to work. Basically, I used to be able to feed in a list of ORCIDs, and get all their works out as a list of dataframes. I found a separate issue (#46) and adapted the code accordingly, but it still returns a 404... 

Thanks very much for your help and this package, it is really awesome.

**Comment by sckott** [comment]
Share some code that fails so I can try it. The code above is sudo code cause I can't run it, e.g., I don't have `ids`

**Comment by joneriks** [comment]
This is resolved, apparently if an ORCID is invalid (e.g. a digit is missing or it doesn't exist) it throws that rather cryptic error of 404 since it can't look up the resource.
Thanks for all your help.

**Comment by sckott** [comment]
Okay. I forget sometimes that HTTP errors (e.g., 404) are not universally understandable - 404 means that it was not found. And I think it says as much:

```r
rorcid::orcid_id("0000-0001-8446-19953")
#> Error: Not Found (HTTP 404).
#>  - 404 Not Found: The resource was not found.
```
