### ISSUE TITLE
More detailed vignette?

### ISSUE THREAD

**Issue by bomeara** [ropensci/rorcid#56]
I'm trying to use this package for CV updating (I had been using an earlier version, but it's changed with the API changes, understandably). I'm trying to just get a formatted list of publications, or at least a series of DOIs I can send elsewhere, but I just can't figure it out. It seems I can get some basic info with a works call, but then have to try to dig through to get the put_code for each, etc. and I'm having trouble wading through the output to easily find this. I imagine going from orcid id to series of nicely formatted citations is a pretty common use case, so having this explained in the vignette would be helpful. Perhaps it's something to do with my orcid record:

```
x <- identifiers(works(orcid_id("0000-0001-8607-8025")))
```

works fine, but for me, `0000-0002-0337-5997`, 

```
x <- identifiers(works(orcid_id("0000-0002-0337-5997")))
```

I get

```
Error in z[tolower(z$`external-id-type`) %in% type, "external-id-value"] : 
  incorrect number of dimensions
```

I think I'm close (maybe it's some weirdly formatted ref in my orcid set of works) but even getting this over an hour of work, digging through documentation, etc.: maybe a vignette example with this and linking out to get properly formatted citations using some other package would help others.

Thanks for the continued development of the package!

**Comment by bomeara** [comment]
[note that the error is resolved with the github version of the package. Yay! Still, adding an example would be a nice enhancement]

**Comment by sckott** [comment]
thanks for the issue @bomeara 

I was going to ask what version of the pkg you were using. So with installing from github you no longer get the error, correct?  

So the example you want is: 

Go from an ORCID identifier to a list/vector of citations for works for that ORCID id

Is that correct?

**Comment by bomeara** [comment]
Thanks, @sckott. Yes, updating to the latest github version fixed the error issue.  Maybe something like:

> One workflow is to get publications associated with an Orcid profile. The following lines will extract all the works with a DOI, use the `rcrossref` package to get nicely formatted references for each, and then export them to a bibtex file

```
my.dois <- rorcid::identifiers(rorcid::works("0000-0002-0337-5997"))
pubs <- rcrossref::cr_cn(dois = my.dois, format = "bibtex", .progress="text")
lapply(pubs, write, "pubs.bib", append=TRUE)
```

This gets well-formatted info for everything with a DOI, but works that lack a DOI aren't included. It may be more consistent than the Orcid bibtex formatting, though. There are probably better ways to do this than the script above, but a use case like this in the vignette could be handy. 

btw, I tried using Carl's Orcid ID (0000-0002-1642-628X), as elsewhere in the vignette, but this seemed to result in errors at the rcrossref step.

**Comment by sckott** [comment]
@bomeara any thoughts?

**Comment by bomeara** [comment]
Thanks -- the addition to the vignette works perfectly for me.
