### ISSUE TITLE
multiple entries for same article in works

### ISSUE THREAD

**Issue by iainmwallace** [ropensci/rorcid#58]
Hi,

Fantastic package! 

One oddity that I am encountering is that on my public profile, https://orcid.org/0000-0002-9491-7025, there are 26 articles but if I pull it in to R I find 50 references. 
       
     my_id<-'0000-0002-9491-7025'
     z<-as.orcid(x = my_id)
     a<-works(z)

There are duplicates in this list of 50, and if I do 

      a$title.title.value%>%unique() 

I get the expected 26 articles.

I am sure this is a user error on how I am creating the bibliography, but I am wondering what might be causing it.

Ultimately, I am trying to get a table that contains  title, pmid and doi but minimizing any queries to pubmed.

Thanks

Iain

**Comment by sckott** [comment]
thanks for the issue @t088 - on vacation now, will respond mid next week

**Comment by sckott** [comment]
I don't know exactly why that is. ORCID returns multiple results for each work, within each work coming from different sources: `Europe PubMed Central and `ResearcherID`

If you do 

```r
a[a$`source.source-name.value` == "Europe PubMed Central",]
```

you can get the 26 you talked about.

**Comment by sckott** [comment]
any thoughts @iainmwallace ?

**Comment by iainmwallace** [comment]
According to orcid, there can be situations were there are duplicate records from different source systems and occasionally there can be a discrepancy in formatting of the title which will mean the unique statement won't work. Ideally the data needs to be fixed at the originating source which hopefully will flow through the research eco-system.

From a practical perspective, I am doing the uniqueness on the title after removing formatting and spaces which has worked well for me.

If I find out how to retrieve the grouping that are present on the orcid page, I will let you know.

**Comment by sckott** [comment]
thanks
