### ISSUE TITLE
upgraded affiliation types

### ISSUE THREAD

**Issue by awconway** [ropensci/rorcid#63]
Are there plans to make the upgraded affiliation types (from October 2018) available to access through rorcid?
- Invited positions and distinctions
- Membership and service
Information about the release is here: https://orcid.org/blog/2018/10/09/new-feature-alert-upgraded-affiliation-types 
Thanks

**Comment by sckott** [comment]
I hadn't heard about it yet. It looks like that's a new version of their API in development, so not something we should be using at this point. Can you sort out where in the API that information is? Maybe ask them

**Comment by awconway** [comment]
Apparently this information will be available in the stable 3.0 version in a month or so. Their response is below. 

> The new affiliation types are currently available in the [3.0 release candidate version](https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources/record_3.0_rc1) of the ORCID API.  The stable 3.0 version will be available in a month or so.

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
will be moving to API v3 soon

**Comment by sckott** [comment]
done in #70
