### ISSUE TITLE
recursive in orcid() fxn doesn't do anything

### ISSUE THREAD

**Issue by sckott** [ropensci/rorcid#65]

**Comment by iainmwallace** [comment]
Also finding this 

orcid(query="Bristol Myers Squibb",recursive = TRUE) will return 100 rows
while
orcid(query="Bristol Myers Squibb",rows=200) will return 200 rows

**Comment by sckott** [comment]
@iainmwallace thanks for the ping. sorry about that, that param wasn't used at all internally in the fxn, removed it.
