### ISSUE TITLE
API version 3 plans?

### ISSUE THREAD

**Issue by iainmwallace** [ropensci/rorcid#68]
Hi,

I was wondering if there were any plans to support v3 of the API that was recently announced https://orcid.org/blog/2019/05/16/orcid-api-30-here? 

One feature that is particularly exciting is the standardization of identifiers.

Thanks

Iain

**Comment by sckott** [comment]
thanks for the ping @iainmwallace  I didn't know about the new API, will subscribe to the blog so I don't miss these in the future

work on branch https://github.com/ropensci/rorcid/tree/api-v3

**Comment by sckott** [comment]
@iainmwallace can install `remotes::install_github("ropensci/rorcid@api-v3")`, reload R, and try it out

**Comment by iainmwallace** [comment]
Looks great!

**Comment by sckott** [comment]
@iainmwallace great, glad it works. will merge soon to master
