### ISSUE TITLE
example calls broken

### ISSUE THREAD

**Issue by emhart** [ropensci/rorcid#8]
All searches with `orcid()` return the same problem:
```
orcid("10.1087/20120404")
Error in strsplit(names(x), "\\.") 
```

**Comment by moreedri** [comment]
the API has changed ; SOLR fields have changed, most of those mentioned in the examples are now gone

http://support.orcid.org/knowledgebase/articles/132354-searching-with-the-public-api

**Comment by sckott** [comment]
@moreedri thanks very much. Will update the package...

**Comment by moreedri** [comment]
I probably should be helping out, but it looks like a major rewrite of the
API and thus of your package?




-- 
Dries Moreels

Ghent University Library
mobile: +32 488 983398




-----Oorspronkelijk bericht-----
Van: Scott Chamberlain <notifications@github.com>
Beantwoorden - Aan: ropensci/rorcid
<reply+00008f831492bfc8d185c1f6a9546d4d3f428f86f15b071a92cf0000000110ec9a39
92a169ce01a761f8@reply.github.com>
Datum: vrijdag 6 februari 2015 16:05
Aan: ropensci/rorcid <rorcid@noreply.github.com>
CC: Dries Moreels <dries.moreels@ugent.be>
Onderwerp: Re: [rorcid] example calls broken (#8)

@moreedri <https://github.com/moreedri> thanks very much. Will update the
package...
—
Reply to this email directly or view it on GitHub
<https://github.com/ropensci/rorcid/issues/8#issuecomment-73249784>.

**Comment by sckott** [comment]
Working on it now... I should have something new soon

**Comment by sckott** [comment]
@moreedri okay, working version up on the master branch now 

see the readme https://github.com/ropensci/rorcid#installation

**Comment by sckott** [comment]
closing this, open any issues as needed
