### ISSUE TITLE
orcid_search parameters (current_prim_inst doesn't work)

### ISSUE THREAD

**Issue by wsphd** [ropensci/rorcid#82]
for orcid_search, affiliation_org works and current_inst works, but for the life of me I can't get current_prim_inst to work.  Any ideas?

**Comment by sckott** [comment]
thanks @wsphd 

looks like the ORCID server is throwing a 500 error that the field doesn't exist. looks like they removed it https://trello.com/c/UUCBZJTU/576-update-search-documentation-after-solr-upgrade recently 

reinstall to get changes `remotes::install_github("ropensci/rorcid")`

Can you use `current_inst` for your purposes?  

In the change I just made here `current_prim_inst` and `patent_number` parameters have been removed from `orcid_search`;  there are some additional fields you can use in the `orcid()` function

**Comment by wsphd** [comment]
Scott,

Thanks for the confirmation.  I thought I was going crazy.  Yes, 
current_inst is OK.  Here's the issue--no two people fill out the ORCID 
form the same way.  So trying to get a "complete" list of individuals by 
institution is non-trivial.

Thanks for all of your hard work.

Wayne

**Comment by sckott** [comment]
I can see how that task would be difficult!
