### ISSUE TITLE
Issue retrieving all orcid ids associated with organization

### ISSUE THREAD

**Issue by iainmwallace** [ropensci/rorcid#83]
Hi,

I am trying to return all of the orcid ids associated with my organization and am running into a small issue - some of the results (near the end of the list) reflect profiles that match part of my organization's name anywhere rather than an exact search in the employment section.

Is there a way to limit to just an exact search in the institution field?

Thanks 

Iain

    bms_ids<-list()
    bms_ids[[1]]<-orcid_search(current_inst="Bristol Myers Squibb", rows=50) 
    bms_ids[[2]]<-orcid_search(current_inst="Bristol Myers Squibb", rows=40,start=50)
    bms_ids[[3]]<-orcid_search(current_inst="Bristol Myers Squibb", rows=5,start=90)
    bms_ids[[4]]<-orcid_search(current_inst="Bristol Myers Squibb", rows=2,start=95)
    ## row 98 is problematic
    #bms_ids_5<-orcid_search(current_inst="Bristol Myers Squibb", rows=1,start=98)
    #Error in data.frame(first = rr[[1]]$name$`given-names`$value, last = rr[[1]]$name$`family- 
    name`$value,  : 
    #arguments imply differing number of rows: 0, 1
    bms_ids[[5]]<-orcid_search(current_inst="Bristol Myers Squibb", rows=200,start=99)
    bms_ids[[6]]<-orcid_search(current_inst="Bristol Myers Squibb", rows=200,start=299)

**Comment by sckott** [comment]
thanks for this. there's 2 separate issues. lets start with the error first. what version of `rorcid` and R do you have? I cannot replicate the error, so perhaps we have different versions

**Comment by iainmwallace** [comment]
Thanks - the error doesn't seem to be happening any more
I am using version 0.6.0.93

I also tried searching just using "Squibb" and I get much more reasonable results (187 returned results, and result 186 is matching the employment)

other attached packages:
  [1] rorcid_0.6.0.93

bms<-list()
bms[[1]]<-orcid_search(current_inst="Bristol Myers Squibb",rows=200)
bms[[2]]<-orcid_search(current_inst="Bristol Myers Squibb",rows=200,start=200)
bms[[3]]<-orcid_search(current_inst="Bristol Myers Squibb",rows=200,start=400)
bms[[4]]<-orcid_search(current_inst="Bristol Myers Squibb",rows=200,start=600)
bms[[4]][4,] # matching Myers surname

squibb<-list()
squibb[[1]]<-orcid_search(current_inst="Squibb",rows=200)
squibb[[1]][187,] # matches an award rather than employment
squibb[[1]][186,] # matches an employment

**Comment by sckott** [comment]
glad the error isn't happening anymore. 

> I also tried searching just using "Squibb" and I get much more reasonable results (187 returned results, and result 186 is matching the employment)

So are you happy with the search results? or still have questions about it?

**Comment by iainmwallace** [comment]
Thanks for checking in - I have made some progress, and am of course delighted with the rorcid package, but still unclear if it is technically possible to get a complete list of all orcid profiles at an organization.

ORCID support recommended that I use escaped quotes around the institution name, as in  Example 14 on the search documentation https://github.com/ORCID/ORCID-Source/blob/master/orcid-api-web/tutorial/search.md#example-14

This has led me to this query, which is better 
     bms<-list()
     bms[[1]]<-orcid_search(current_inst="%22Bristol-Myers%20Squibb%22",rows=200,start=1)
      bms[[2]]<-orcid_search(current_inst="%22Bristol-Myers%20Squibb%22",rows=200,start=200)

One source of confusion is the result numbers differ from the search options on the website, but I understand that is because the api doesn't necessarily map 1:1

**Comment by sckott** [comment]
It would make sense to be able to get all orcid's within an organization, wish they made that easier. 

Yeah, hard to know what exactly they do on their website, even if they do use their own API that we use here, they may modify its behavior in their website app code

**Comment by sckott** [comment]
closing. don't think there's anything i can do here
