### ISSUE TITLE
orcid_works() doesn't have the "author" information?

### ISSUE THREAD

**Issue by yu-soong** [ropensci/rorcid#90]
The `orcid_works("XXXX-XXXX-XXXX-XXXX") ` gives the information of "title", "doi", "journal"... but not "author" information of papers. I checked the web of ORCID, it would be the "Contributor" under "Works" entry. Did I miss something, otherwise is it possible to have the author information in the next version of `rorcid`? Tnanks!
--Yu

**Comment by sckott** [comment]
We don't remove any data from the results from ORCID in `orcid_works` function, so ORCID must not give the author information. 

Try https://docs.ropensci.org/rorcid/reference/orcid_citations.html -

**Comment by yu-soong** [comment]
Thanks sckott, I am using other packages like `scholar` and `bib2df` to get the author information.
